name: Daily Leads Report

on:
  schedule:
    - cron: "30 3 * * *"  # ✅ Runs at 05:30 Madrid time
  workflow_dispatch:

 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autoEmail.py
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ODOO_URL: ${{ secrets.ODOO_URL }}
          ODOO_DB: ${{ secrets.ODOO_DB }}
          ODOO_API_KEY: ${{ secrets.ODOO_API_KEY }}
          ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}
        run: python autoEmail.py
