# .github/workflows/monthlyCategorizedLeads.yml
name: Monthly Categorized Leads Report

on:
  schedule:
    - cron: '0 6 1 * *'    # → 06:00 UTC on the 1st of every month
  workflow_dispatch:        # allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monthly report script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ODOO_URL:      ${{ secrets.ODOO_URL }}
          ODOO_DB:       ${{ secrets.ODOO_DB }}
          ODOO_API_KEY:  ${{ secrets.ODOO_API_KEY }}
          ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}
        run: python weekly_categorized_leads.py   # same script, now executed monthly
