name: Push Odoo Leads to Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # every day at 04:00 UTC

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode Google creds
        run: |
          echo "${{ secrets.GSHEET_CREDS_B64 }}" | base64 -d > credentials.json

      - name: Run upload script
        env:
          ODOO_URL:               ${{ secrets.ODOO_URL }}
          ODOO_DB:                ${{ secrets.ODOO_DB }}
          ODOO_USERNAME:          ${{ secrets.ODOO_USERNAME }}
          ODOO_API_KEY:           ${{ secrets.ODOO_API_KEY }}
          GSHEET_SPREADSHEET_ID:  "1pcn9IrmpSO4oFvyHpbBsZDyocqRbukLAdfVNbnITtdU"
        run: python upload_odoo_leads.py
